version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
#    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db